### PR TITLE
hair guides extension + simple canvas samples

### PR DESCRIPTION
**Pull request by helgemathee**

### CODE REVIEW

**Comment by helgemathee** [comment]
Please review the samples + test, once ok please merge. I can merge this into SceneGraph on escher once approved.

**Comment by helgemathee** [comment]
just added the maya sample scenes from Tom

**Comment by mootzoid** [comment]
The (standalone) samples are really good, I like how they slowly get more complex, it's like a tutorial.

The last sample ("custom_manipulation") confused me a bit though.
After activating the manipulation tool I was expecting that I could tweak the points of the main guides and see how the ones in between update. Maybe we can modify this sample so that it does exactly that?

Will check the Maya samples now.

**Comment by mootzoid** [comment]
The Maya samples work and look great!

Really great production sample, we can merge this as far as I am concerned (with or without the modified "custom_manipulation" sample).

**Comment by helgemathee** [comment]
thanks - improved the manipulation sample.

**Pull request merged**
